version: "3.7"
services:
  database:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes: 
      - ./pgdata:/var/lib/postgres/
    ports:
      - "5432:5432"